### ISSUE TITLE
Opa constraints (enforce Lifecycle lable to compare with project I'd  )

### ISSUE THREAD

**Issue by rakesh0022** [open-policy-agent/community#233]
L
![16574196432596895586312101289443](https://user-images.githubusercontent.com/92107358/178128739-bccd701a-0503-4de2-9e5b-cc51bf0a27b7.jpg

I am trying to write a policy to check if lifecycle label is any of the value of {dev, qa ,cert-cde, prod-cde,svcs,cert-ncde,prod-ncde}

The logic is working when I entered lifecycle label as prod or dev apart for other lifecycle labels value the conditions is not getting fails

**Comment by srenatus** [comment]
Now a discussion topic.
